<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/style.css'); ?>
        <?php
        if ($this->jQuery()->isEnabled()) {
            $this->jQuery()->uiEnable();
            $this->jQuery()->setLocalPath($this->baseUrl() . '/js/jquery/jquery-1.4.3.min.js')
                    ->setUiLocalPath($this->baseUrl() . '/js/jquery/jquery-ui-1.8.6.custom.min.js')
                    ->addStyleSheet($this->baseUrl() . '/css/jquery-ui/black-tie/jquery-ui-1.8.6.custom.css');
            echo $this->jQuery();
        }
        ?>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-20097300-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>

    </head>
    <body>
        <div id="page_container" class="full_width">
            <!-- header -->
            <div id="header" class="full_width">
                <div class="aparat"></div>
                <div class="logo"></div>
                <?php echo $this->render('navigation.phtml'); ?>
            </div>
            <!-- content -->
            <div id="content" class="full_width">
                <?php echo $this->layout()->content; ?>
            </div>
            <!-- footer -->
            <div id="footer" class="full_width">
                Opracował: Kamil Zieliński &copy 2010
            </div>
        </div>
    </body>
</html>