<?php $this->jQuery()->enable(); ?>

<div class="ui-state-active ui-corner-all center"
     style="padding: 10px; width: 690px; margin-top: 20px;
     position: relative;
     z-index: 2;
     ">
    <h3>Praca dyplomowa (inżynierska)</h3>
    <p>
        Opracowanie programu ułatwiającego zarządzanie zbiorem zdjęć cyfrowych.
        Katalogowanie zdjęć z przechowywaniem  metadanych (EXIF, IPTC) w bazie danych.
        Edycja metadanych. Przeszukiwanie bazy wg słów kluczowych,
        przeszukiwanie z operatorami logicznymi: & (i), + (lub), ! (nie). Przykład: tag1 & !tag2.
        „Geotagowanie” zdjęć z użyciem Google Maps.
        Realizacja jako aplikacja internetowa.
    </p>
    <a class="ui-state-highlight" href="http://code.google.com/p/zieli/" target="_blank">Strona projektu</a>
    Znalezione bugi proszę zgłaszać w zakładce issues na stronie projektu.
</div>

<div class="center"
    style="
     position: relative;
     margin-top: -60px;
     ">
    <img src="images/sample2.png" alt=""/>
</div>